version: '3.8'

services:
  registry:
    container_name: registry
    image: public.ecr.aws/docker/library/registry:latest
    ports:
    - "8000:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./data:/data
